### ISSUE TITLE
Decide JSON Format

### ISSUE THREAD

**Issue by hshindo** [hshindo/jukainlp-web#6]
My idea is as follows.

``` javascript
{
    "sentence": [
        [1,13], [15,24],
    ],
    "pos": [
        [1,1,"NNP"], [3,6,"VBP"], [8,8,"DT"], [10,13,"NN"],
        [15,16,"NNP"], [18,19,"VBP"], [21,24,"JJ"],
    ],
    "entity": [
        [1,6,"PERSON"], [15,19,"LOCATION"],
    ],
    "trans-ja": [
        "私はペンを持っています。",
        "彼は親切です。"
    ],
    "trans_en": [
        "I have a pen.",
        "He is kind",
    ],
    "trans_cn": [
        "我有一支笔。",
        "他人很好",
    ],
}
```

Each span indicates the start and end range indexes.
I prefer this style because it is compact, extensible, and easy to create for server-side.

**Comment by hshindo** [comment]
I was suggested to use an another format as follows:

``` javascript
      "list_sentence": 
        [
          {
            "ne": {
              "name": "PERSON",
            },
            "wiki": "Darth Vader",
            "items": [
                {
                  "pos": "NNP",
                  "name": "Darth",
                },
                {
                  "pos": "NNP",
                  "name": "Vador",
                }
              ]
          },
          {
            "ne": {
              "name": "PERSON",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "",
                  "name": ",",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "RB",
                  "name": "also",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "RB",
                  "name": "known",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "IN",
                  "name": "as",
                }
              ]
          },
          {
            "ne": {
              "name": "PERSON",
            },
            "wiki": "Darth Vader",
            "items": [
                {
                  "pos": "NNP",
                  "name": "Anakin",
                },
                {
                  "pos": "NNP",
                  "name": "Skywalker",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "VBZ",
                  "name": "is",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "DT",
                  "name": "a",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "JJ",
                  "name": "fictional",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": "NN",
                  "name": "character",
                }
              ]
          },
          {
            "ne": {
              "name": "",
            },
            "wiki": "",
            "items": [
                {
                  "pos": ".",
                  "name": ".",
                }
              ]
          }
        ],
      "trans_en":"Darth Vador, also known as Anakin Skywalker is a fictional character.",
      "trans_ja":"",
      "trans_cn":""
```

This is verbose.

My question:
The spans of pos, ne, and wiki might be overlapped.
How would you handle such a case?
For example, 
- pos: "Darth"
- ne: "Darth Vador"
- wiki: "Vador, also known"

could be possible.

**Comment by mickey-ichi** [comment]
As indicated in the Jukai_NLP_UI-en.pdf, we need to return ne, wiki and pos from a sentence. In your idea, it will only detect pos and entity (I am not sure whether entity is similar to ne, but if [1,6,"PERSON"] then "I have" = PERSON, which is not really making sense for me). 

We suggest that we should detect all ne, wiki, pos at the same time. As shown in the file, they could be overlapped. So I dont really get your question here :)
<img width="958" alt="screen shot 2016-10-21 at 2 40 06 pm" src="https://cloud.githubusercontent.com/assets/13127169/19590657/311aedf4-979d-11e6-832d-b7399dd9d692.png">

**Comment by hshindo** [comment]
I see.
The range: [1,6,"PERSON"] is just an example.
In my example, only "pos" and "entity" are contained, but "wiki" could be contained as well.

Here is what I want to say:  
"Overlapped, not included":
- ne: "Darth Vador"
- wiki: "Vador, also known"

"Overlapped, included":
- "ne": "Darth Vador"
- "wiki": "Darth"

I want to know how to handle the case of "overlapped, not included"?
In your example JSON, it seems that you ASSUME that ne and wiki are same span, and pos is always included in ne and wiki. However, it happens that ne, wiki, and pos are overlapped, but not included.

Since the server doesn't always analyze texts correctly, we should be able to handle such cases.

**Comment by mickey-ichi** [comment]
As you can see in my example, ne is detected as "Darth Vador" and wiki is derived from ne. They will be wrapped in the same way so in most case they will be the same. I could not think of any other cases where ne is different than wiki
<img width="835" alt="screen shot 2016-10-21 at 3 18 03 pm" src="https://cloud.githubusercontent.com/assets/13127169/19591502/9e1f01ac-97a1-11e6-953c-eaaea8d1897d.png">

**Comment by hshindo** [comment]
The ne analyzer and wiki analyzer are independent, so it happens.
Could you tell me what exactly is the problem of my JSON format? I could fix it.

**Comment by mickey-ichi** [comment]
I think with your JSON format, it will be time-consuming for server to be implement (compared to our format, it has to take out the start and end range indexes) and the UI needs to modify to be compatible with your JSON format. 
If you are keen on working on your format, could you please provide us the description, i.e. an example of JSON format for a full sentence?

**Comment by hshindo** [comment]
Thank you for your comment.
I'll change the format. Let me think about it.

**Comment by hshindo** [comment]
I changed the format as follows:

``` javascript
[
  {
    // first sentence
    text: "Darth Vador, also known as Anakin Skywalker is a fictional character.",
    anno: [
      ["wiki", 0, 10, "Darth Vador"],
      ["ne", 0, 10, "PERSON"],
      ["pos", 0, 4, "NNP"],
    ],
    trans-ja: "ダースベイダー（アナキンスカイウォーカーとしても知られている）は，架空の人物だ．",
    trans-cn: "达思Vador，也被称为天行者阿纳金是一个虚构的人物。",
  },
  {
    // second sentence
    text: "He is originally a good person, but",
    anno: [
      ["pos", 0, 1, "PRP"],
    ]
  },
]
```

The span range is start and end character indexes.

Following the above json format, we're developing an independent react-based visualization library: [react-nlp](https://github.com/hshindo/react-nlp), which is an alternative to brat.

react-nlp is a general framework, and independent from any specific annotation layers such as "pos", "ne" and "wiki". It just visualizes input texts and span annotations.

My plan is to develop react-nlp further, and call it from jukainlp-web.

If possible, could you look at the react-nlp and refine functions and styles (css, etc.), as you had done before to jukainlp-web?
You can run a demo of react-nlp. See the section of "Run Example".

**Comment by hshindo** [comment]
Pull-request to react-nlp is very welcome!

**Comment by mickey-ichi** [comment]
I checked the above sentence, and seems like it detects wrong entity.

Also for react-nlp, is it possible for me to change everywhere needed? I am afraid that if I change just functions and styles, it might not work as expected.

<img width="1680" alt="screen shot 2016-11-01 at 10 35 02 am" src="https://cloud.githubusercontent.com/assets/13127169/19878775/59a90cb2-a01f-11e6-93e8-542d89338c7a.png">

**Comment by hshindo** [comment]
Thanks for checking.
Currently, the server-side text analysis is just random. So, no worry about the results.

Yes, it's possible to change anything you need.
As you had done before, we'd appreciate if you could send a pull-request to react-nlp.
Our react-nlp engineer will review the pull-request and merge it.

Note that react-nlp only provides a visualization function (i.e., right side on your JukaiNLP figure).
Thus, menu-bar and react-ace editor should NOT be contained in react-nlp.

**Comment by hshindo** [comment]
@mickey-ichi 
I'm not sure, but does jukainlp-web already have the same functionality as react-nlp?
If so, it is unnecessary to modify react-nlp. react-nlp is just a prototype.
Alternatively, just separating the visualization part in jukainlp-web from menu-bar and ace editor is fine.

**Comment by hshindo** [comment]
@mickey-ichi 

Basic plan:
- Separate the visualization function as an independent library (alternative to brat)
  - based on react-nlp? , jukainlp-web? or merge?
- Add jukainlp-web as an example of the visualization library

**Comment by mickey-ichi** [comment]
@hshindo 

Okay. For the first point, I will merge those two :)

**Comment by hshindo** [comment]
@mickey-ichi 

Thank you! You could drastically change react-nlp.

**Comment by mickey-ichi** [comment]
@hshindo you said earlier that "Currently, the server-side text analysis is just random. So, no worry about the results."

Could you please resolve the server-side text analysis somehow for me to test?

**Comment by hshindo** [comment]
@mickey-ichi

Is it in a hurry?
Since server-side programs (machine learning stuff) needs big improvements, we're actively rewriting codes.
It will take some time.

**Comment by hshindo** [comment]
If you want to test, could you change the response from the server randomly on a client-side for now?
Or, change the response as you want using some heuristic rule.
I'm sure this is sufficient for testing.

**Comment by mickey-ichi** [comment]
@hshindo : 

Okay, could you give me a full data sample to test?

**Comment by hshindo** [comment]
@mickey-ichi 

The correct annotations (POS, NE, etc.) are not publicly available.
That's why I recommend to test by random annotations.
Please use any texts you want for testing.

For instance, take texts from [Obama (wikipedia)](https://en.wikipedia.org/wiki/Barack_Obama) .
Person's name, nations, company names should be annotated as "NE".
